language: cpp

env:
- QT_SELECT=qt5

compiler:
- g++

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install g++-4.8;
  - wget -O Qt5.2.0.tar.xz https://www.dropbox.com/s/mkqtb8teeydsmrk/Qt5.2.0.tar.xz?dl=0
  - mkdir ~/Qt5.2.0
  - tar -xJf Qt5.2.0.tar.xz -C ~/Qt5.2.0
  - sudo chmod -R 777 ~/Qt5.2.0/
  - export CXX="g++-4.8"
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  
script:
  - ~/Qt5.2.0/5.2.0/gcc_64/bin/qmake FactDev.pro -r -spec linux-g++ CONFIG+=debug
  - make -j9
  - LD_LIBRARY_PATH=`pwd`/src
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH
  - ls $LD_LIBRARY_PATH/*.so*
  - ln -s `pwd`/src/sql `pwd`/tests/sql
  - cd tests
  - ./tests
  - lcov --capture --directory ../src --output-file coverage.info
  - lcov -r coverage.info ~/Qt5.2.0/5.2.0/gcc_64/\* /usr/include/\* /home/travis/build/FACT-Team/FactDev/src/gui/\* /home/travis/build/FACT-Team/FactDev/src/moc_\* /home/travis/build/FACT-Team/FactDev/src/ui_\* /home/travis/build/FACT-Team/FactDev/src/qrc_\* -o coverage.info
  - coveralls-lcov coverage.info
