language: cpp

env:
- QT_SELECT=qt5

compiler:
  - g++

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5core5 qt5-qmake qt5-default qtchooser
  
install:
  - sudo apt-get install gcc-4.8 g++-4.8;
  - export CXX="g++-4.8"
  
script:
- qmake && make -j3 && ./tests
