language: cpp

env:
- QT_SELECT=qt5
   global:
      - GCC_VERSION="4.8"
      
compiler:
  - gcc
  - clang
  
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang 3.4
- if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
- sudo apt-get update -qq
- sudo apt-get install -qq libqt5core5 qt5-qmake qt5-default qtchooser

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq "libstdc++-${GCC_VERSION}-dev"; fi
  
script:
- qmake && make -j3 && ./tests
