INSERT INTO `Contributory` VALUES(1,'Une descriptoin', 'une description un petit peu longue',42,0 );
INSERT INTO `Contributory` VALUES(2,'Chouette', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(3,'Salut !', 'une description un petit peu longue',5,0);
INSERT INTO `Contributory` VALUES(4,'Manger', 'une description un petit peu longue', 0,1);
INSERT INTO `Contributory` VALUES(5,'Salut', 'une description un petit peu longue',10,0);
INSERT INTO `Contributory` VALUES(6,'Coucou', 'une description un petit peu longue',5,1);
INSERT INTO `Contributory` VALUES(7,'Nooon', 'une description un petit peu longue',2,0);
INSERT INTO `Contributory` VALUES(8,'Ouiiii!', 'une description un petit peu longue',5,0);
INSERT INTO `Contributory` VALUES(9,'Allo', 'une description un petit peu longue',10,1);
INSERT INTO `Contributory` VALUES(10,'Manger', 'une description un petit peu longue',2,1);
INSERT INTO `Contributory` VALUES(11,'Trouver', 'une description un petit peu longue',12,0);
INSERT INTO `Contributory` VALUES(12,'Danser', 'une description un petit peu longue',5,0);
INSERT INTO `Contributory` VALUES(13,'Checher', 'une description un petit peu longue',5,1);
INSERT INTO `Contributory` VALUES(14,'Un', 'une description un petit peu longue',0,0);
INSERT INTO `Contributory` VALUES(15,'Soleil', 'une description un petit peu longue',10,1);
INSERT INTO `Contributory` VALUES(16,'Deux', 'une description un petit peu longue',14,0);
INSERT INTO `Contributory` VALUES(17,'Trois', 'une description un petit peu longue',12,1);
INSERT INTO `Contributory` VALUES(18,'Coucou', 'une description un petit peu longue',7,0);
INSERT INTO `Contributory` VALUES(19,'Boubou', 'une description un petit peu longue',14,1);
INSERT INTO `Contributory` VALUES(20,'Babar', 'une description un petit peu longue',14,0);
INSERT INTO `Contributory` VALUES(21,'eau', 'une description un petit peu longue',2,1);
INSERT INTO `Contributory` VALUES(22,'feu', 'une description un petit peu longue',4,0);
INSERT INTO `Contributory` VALUES(23,'terre', 'une description un petit peu longue',3,0);
INSERT INTO `Contributory` VALUES(24,'Manger', 'une description un petit peu longue',14,1);
INSERT INTO `Contributory` VALUES(25,'tuy', 'une description un petit peu longue',3,0);
INSERT INTO `Contributory` VALUES(26,'MACHIN', 'une description un petit peu longue',2,1);
INSERT INTO `Contributory` VALUES(27,'ouiu', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(28,'feu', 'une description un petit peu longue',14,0);
INSERT INTO `Contributory` VALUES(29,'gui', 'une description un petit peu longue',4,1);
INSERT INTO `Contributory` VALUES(30,'oui', 'une description un petit peu longue',1,0);
INSERT INTO `Contributory` VALUES(31,'41', 'une description un petit peu longue',14,1);
INSERT INTO `Contributory` VALUES(32,'Diner', 'une description un petit peu longue',4,0);
INSERT INTO `Contributory` VALUES(33,'FUmer', 'une description un petit peu longue',4,0);
INSERT INTO `Contributory` VALUES(34,'Fraise', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(35,'Des bois', 'une description un petit peu longue',7,0);
INSERT INTO `Contributory` VALUES(36,'lili', 'une description un petit peu longue',7,1);
INSERT INTO `Contributory` VALUES(37,'lio', 'une description un petit peu longue',4,1);
INSERT INTO `Contributory` VALUES(38,'Manger', 'une description un petit peu longue',4,1);
INSERT INTO `Contributory` VALUES(39,'Puiser', 'une description un petit peu longue',4,1);
INSERT INTO `Contributory` VALUES(40,'', 'une description un petit peu longue',0,1);
INSERT INTO `Contributory` VALUES(41,'PAPA', 'une description un petit peu longue',4,0);
INSERT INTO `Contributory` VALUES(42,'Avaler', 'une description un petit peu longue',2,0);
INSERT INTO `Contributory` VALUES(43,'Macher', 'une description un petit peu longue',4,0);
INSERT INTO `Contributory` VALUES(44,'Recracher', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(45,'Manger', 'une description un petit peu longue',1,0);
INSERT INTO `Contributory` VALUES(46,'Donut', 'une description un petit peu longue',6,0);
INSERT INTO `Contributory` VALUES(47,'Lion', 'une description un petit peu longue',14,1);
INSERT INTO `Contributory` VALUES(48,'No homo', 'une description un petit peu longue',3,0);
INSERT INTO `Contributory` VALUES(49,'Puits', 'une description un petit peu longue',4,1);
INSERT INTO `Contributory` VALUES(50,'Pétrole', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(51,'Meurt', 'une description un petit peu longue',3,0);
INSERT INTO `Contributory` VALUES(52,'Vit', 'une description un petit peu longue',4,1);
INSERT INTO `Contributory` VALUES(53,'Maman', 'une description un petit peu longue',4,0);
INSERT INTO `Contributory` VALUES(54,'Porte une robe', 'une description un petit peu longue',2,0);
INSERT INTO `Contributory` VALUES(55,'Chouette !', 'une description un petit peu longue',12,0);
INSERT INTO `Contributory` VALUES(56,'Kamoulox', 'une description un petit peu longue',0,1);
INSERT INTO `Contributory` VALUES(57,'Salut !', 'une description un petit peu longue',21,1);
INSERT INTO `Contributory` VALUES(58,'Chouette !', 'une description un petit peu longue',0,1);
INSERT INTO `Contributory` VALUES(59,'Coucou.', 'une description un petit peu longue',12,0);
INSERT INTO `Contributory` VALUES(60,'Salut :-)', 'une description un petit peu longue',3,0);
INSERT INTO `Contributory` VALUES(61,'Chouette la descriptoin', 'une description un petit peu longue',1337,1);
INSERT INTO `Contributory` VALUES(62,'Youhou !', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(63,'=)', 'une description un petit peu longue',2,1);
INSERT INTO `Contributory` VALUES(64,'^_^', 'une description un petit peu longue',2,0);
INSERT INTO `Contributory` VALUES(65,'Chose machin chose', 'une description un petit peu longue',23,0);
INSERT INTO `Contributory` VALUES(66,'^qsdlbfj lq sdl jsq jsd', 'une description un petit peu longue',21,0);
INSERT INTO `Contributory` VALUES(67,'J''aime bien Doctor Who ! ', 'une description un petit peu longue',21,0);
INSERT INTO `Contributory` VALUES(68,'Coucou la descriptoin de la mort qui tue ', 'une description un petit peu longue',22,1);
INSERT INTO `Contributory` VALUES(69,'Un bon steak bien saignant !', 'une description un petit peu longue',2,1);
INSERT INTO `Contributory` VALUES(70,'Découpe de jambon', 'une description un petit peu longue',22,1);
INSERT INTO `Contributory` VALUES(71,'Ahaha', 'une description un petit peu longue',23,1);
INSERT INTO `Contributory` VALUES(72,'Coucou.', 'une description un petit peu longue',22,1);
INSERT INTO `Contributory` VALUES(73,'Ouais, et toi ? ', 'une description un petit peu longue',22,0);
INSERT INTO `Contributory` VALUES(74,'Tranquillou :)', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(75,'Salut', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(76,'Ça va ?', 'une description un petit peu longue',21,0);
INSERT INTO `Contributory` VALUES(77,'Café-pas-mal-de-la-fac', 'une description un petit peu longue',6,1);
INSERT INTO `Contributory` VALUES(78,'Café-pas-bon-de-la-fac', 'une description un petit peu longue',1,1);
INSERT INTO `Contributory` VALUES(79,'Expresso', 'une description un petit peu longue',21,1);
INSERT INTO `Contributory` VALUES(80,'Ristretto', 'une description un petit peu longue',30,0);
INSERT INTO `Contributory` VALUES(81,'Café-pas-mal-de-liut', 'une description un petit peu longue',8,1);
