INSERT INTO "Contributory" VALUES(1,'Une descriptoin',42);
INSERT INTO "Contributory" VALUES(2,'Chouette',1);
INSERT INTO "Contributory" VALUES(3,'Salut !',5);
INSERT INTO "Contributory" VALUES(4,'Manger',0);
INSERT INTO "Contributory" VALUES(5,'Salut',10);
INSERT INTO "Contributory" VALUES(6,'Coucou',5);
INSERT INTO "Contributory" VALUES(7,'Nooon',2);
INSERT INTO "Contributory" VALUES(8,'Ouiiii!',5);
INSERT INTO "Contributory" VALUES(9,'Allo',10);
INSERT INTO "Contributory" VALUES(10,'Manger',2);
INSERT INTO "Contributory" VALUES(11,'Trouver',12);
INSERT INTO "Contributory" VALUES(12,'Danser',5);
INSERT INTO "Contributory" VALUES(13,'Checher',5);
INSERT INTO "Contributory" VALUES(14,'Un',0);
INSERT INTO "Contributory" VALUES(15,'Soleil',10);
INSERT INTO "Contributory" VALUES(16,'Deux',14);
INSERT INTO "Contributory" VALUES(17,'Trois',12);
INSERT INTO "Contributory" VALUES(18,'Coucou',7);
INSERT INTO "Contributory" VALUES(19,'Boubou',14);
INSERT INTO "Contributory" VALUES(20,'Babar',14);
INSERT INTO "Contributory" VALUES(21,'eau',2);
INSERT INTO "Contributory" VALUES(22,'feu',4);
INSERT INTO "Contributory" VALUES(23,'terre',3);
INSERT INTO "Contributory" VALUES(24,'Manger',14);
INSERT INTO "Contributory" VALUES(25,'tuy',3);
INSERT INTO "Contributory" VALUES(26,'MACHIN',2);
INSERT INTO "Contributory" VALUES(27,'ouiu',1);
INSERT INTO "Contributory" VALUES(28,'feu',14);
INSERT INTO "Contributory" VALUES(29,'gui',4);
INSERT INTO "Contributory" VALUES(30,'oui',1);
INSERT INTO "Contributory" VALUES(31,'41',14);
INSERT INTO "Contributory" VALUES(32,'Diner',4);
INSERT INTO "Contributory" VALUES(33,'FUmer',4);
INSERT INTO "Contributory" VALUES(34,'Fraise',1);
INSERT INTO "Contributory" VALUES(35,'Des bois',7);
INSERT INTO "Contributory" VALUES(36,'lili',7);
INSERT INTO "Contributory" VALUES(37,'lio',4);
INSERT INTO "Contributory" VALUES(38,'Manger',4);
INSERT INTO "Contributory" VALUES(39,'Puiser',4);
INSERT INTO "Contributory" VALUES(40,'',0);
INSERT INTO "Contributory" VALUES(41,'PAPA',4);
INSERT INTO "Contributory" VALUES(42,'Avaler',2);
INSERT INTO "Contributory" VALUES(43,'Macher',4);
INSERT INTO "Contributory" VALUES(44,'Recracher',1);
INSERT INTO "Contributory" VALUES(45,'Manger',1);
INSERT INTO "Contributory" VALUES(46,'Donut',6);
INSERT INTO "Contributory" VALUES(47,'Lion',14);
INSERT INTO "Contributory" VALUES(48,'No homo',3);
INSERT INTO "Contributory" VALUES(49,'Puits',4);
INSERT INTO "Contributory" VALUES(50,'Pétrole',1);
INSERT INTO "Contributory" VALUES(51,'Meurt',3);
INSERT INTO "Contributory" VALUES(52,'Vit',4);
INSERT INTO "Contributory" VALUES(53,'Maman',4);
INSERT INTO "Contributory" VALUES(54,'Porte une robe',2);
