INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ullamcorper, nisl",40);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dui. Cum",52);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("in, cursus et, eros. Proin ultrices. Duis volutpat",61);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Cras lorem",60);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Nulla tempor augue ac ipsum. Phasellus",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("at fringilla purus mauris a",33);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sit amet, consectetuer",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Nullam velit dui, semper",59);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("elit. Curabitur sed tortor. Integer",37);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("magna, malesuada vel, convallis in, cursus et, eros.",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ipsum",31);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("montes, nascetur ridiculus mus. Donec dignissim magna a tortor.",9);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede blandit congue. In scelerisque scelerisque dui. Suspendisse",14);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("venenatis lacus. Etiam",3);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sed tortor. Integer aliquam adipiscing lacus. Ut nec",60);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("in magna.",44);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("erat nonummy ultricies",28);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("iaculis odio. Nam interdum enim non nisi. Aenean",14);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("massa rutrum",17);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ante ipsum primis in faucibus orci luctus",11);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("et nunc. Quisque ornare tortor at risus. Nunc ac",37);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vitae",44);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("urna. Vivamus molestie",5);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Vivamus euismod urna. Nullam lobortis quam",36);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Maecenas",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Aliquam tincidunt, nunc ac",48);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("diam. Sed diam",5);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dolor. Fusce feugiat. Lorem ipsum dolor sit amet,",22);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tincidunt aliquam arcu. Aliquam ultrices",32);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("lacus.",51);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("lectus pede et",32);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ultricies ligula.",44);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula.",34);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Integer sem elit, pharetra",48);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dignissim tempor arcu. Vestibulum ut eros non",17);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nulla ante, iaculis nec, eleifend non,",16);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies",24);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dui, in sodales elit erat vitae risus.",61);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("quis",9);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vitae risus. Duis a mi fringilla mi",61);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nunc est, mollis non, cursus non, egestas a, dui. Cras",38);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ornare, libero at auctor ullamcorper, nisl arcu iaculis",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sollicitudin a,",50);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("id, ante. Nunc mauris",47);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In",1);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("convallis dolor. Quisque tincidunt pede ac urna. Ut",27);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pellentesque eget, dictum",35);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla",13);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("fringilla ornare placerat, orci lacus vestibulum lorem,",28);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("odio.",27);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nisi. Cum sociis natoque penatibus et magnis",53);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci.",31);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Praesent eu",1);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("amet diam eu dolor egestas rhoncus. Proin nisl sem,",9);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("felis ullamcorper viverra.",41);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("id nunc interdum feugiat. Sed nec metus",58);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ipsum porta elit, a feugiat tellus lorem eu",58);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vehicula. Pellentesque tincidunt tempus risus. Donec",31);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet,",9);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ultrices.",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",36);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sed leo. Cras vehicula aliquet libero. Integer in",18);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non massa non ante bibendum ullamcorper. Duis",17);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nisl. Quisque",35);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("et, rutrum",25);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("orci, consectetuer euismod est arcu ac",52);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("euismod urna.",57);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dui nec urna suscipit nonummy. Fusce",30);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Donec feugiat metus sit amet ante. Vivamus non lorem vitae",3);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("lobortis, nisi",43);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc",33);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("elementum purus, accumsan interdum libero dui",39);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("lacus pede sagittis augue, eu",27);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("magna, malesuada vel, convallis in, cursus et,",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non, luctus sit amet, faucibus ut, nulla. Cras eu",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Nulla semper tellus id",34);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede sagittis augue,",28);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit",18);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("cursus purus. Nullam scelerisque neque sed",49);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("velit. Pellentesque ultricies",51);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("eu odio tristique pharetra. Quisque",16);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy",44);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("aliquam adipiscing lacus. Ut",51);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("neque pellentesque massa",26);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("netus et malesuada fames ac",31);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("est mauris, rhoncus id, mollis nec, cursus a, enim.",54);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ipsum primis in faucibus orci luctus et ultrices posuere",40);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("metus. Vivamus euismod urna. Nullam lobortis",26);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("eu, odio. Phasellus at augue id ante",3);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Duis elementum, dui",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("porttitor",24);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut",30);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Nunc ullamcorper, velit in aliquet lobortis, nisi nibh",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("facilisis facilisis, magna tellus",37);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tempus mauris erat eget ipsum. Suspendisse sagittis.",13);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc",14);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nunc sit amet metus. Aliquam erat volutpat. Nulla",19);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("natoque penatibus et magnis dis parturient",48);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("augue malesuada malesuada. Integer id magna et ipsum cursus",22);

INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("consectetuer mauris id sapien. Cras dolor",46);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("amet lorem semper auctor. Mauris vel",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Aliquam rutrum lorem ac risus. Morbi",51);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nunc est, mollis non,",48);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("elementum, dui quis",61);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dignissim magna a tortor.",55);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("auctor, velit eget laoreet posuere, enim nisl elementum purus,",21);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("adipiscing lobortis risus. In mi",8);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tristique pellentesque, tellus sem mollis dui, in sodales elit",9);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("fermentum fermentum arcu. Vestibulum ante ipsum primis in",56);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("at lacus. Quisque purus sapien, gravida non, sollicitudin a,",13);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("orci sem eget massa. Suspendisse eleifend. Cras sed",41);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("arcu. Aliquam ultrices",2);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede, ultrices a, auctor non, feugiat nec, diam. Duis mi",5);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi",58);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Quisque imperdiet, erat",22);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("commodo",24);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Curabitur",58);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede. Suspendisse dui. Fusce diam nunc, ullamcorper",41);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Suspendisse sed dolor. Fusce mi lorem, vehicula",40);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede. Cras vulputate velit eu sem. Pellentesque",24);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("aliquet",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("diam lorem, auctor",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("est ac facilisis facilisis, magna",5);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("enim diam vel arcu. Curabitur ut odio",39);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vitae risus. Duis a mi fringilla mi",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("in, tempus eu, ligula. Aenean euismod mauris eu elit.",34);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Vivamus sit amet risus. Donec egestas. Aliquam",49);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("elementum, dui quis accumsan convallis, ante lectus convallis",48);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("elit erat vitae risus. Duis a mi fringilla",1);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("risus. In",6);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum",17);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede, nonummy ut, molestie in, tempus",57);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Quisque",13);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non magna.",1);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Cum sociis natoque penatibus et magnis",11);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae,",58);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sed libero. Proin",29);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pharetra. Nam ac nulla. In tincidunt congue turpis.",3);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ornare tortor at risus. Nunc ac sem ut",50);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Maecenas mi felis, adipiscing",6);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede nec ante blandit viverra. Donec",41);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("in molestie tortor nibh sit",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("neque.",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tempor erat neque non",49);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc",15);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("arcu ac orci.",61);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("lectus rutrum urna, nec luctus felis purus ac tellus.",5);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("eu dolor egestas rhoncus.",39);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("cursus et, eros. Proin ultrices.",18);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tempus",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("imperdiet nec, leo. Morbi neque",33);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non, dapibus",1);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("euismod enim. Etiam gravida molestie arcu. Sed eu nibh",43);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ipsum ac mi eleifend egestas. Sed pharetra,",30);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nec metus facilisis lorem tristique",30);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Sed et libero. Proin mi. Aliquam gravida",24);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed",7);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("facilisis. Suspendisse commodo tincidunt nibh. Phasellus",55);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Aliquam ornare, libero at auctor",37);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Lorem ipsum dolor sit amet, consectetuer",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Integer vitae nibh. Donec est mauris, rhoncus id,",33);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("eu, euismod",14);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("In ornare sagittis felis. Donec tempor, est",19);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("molestie orci tincidunt",36);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Suspendisse",59);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("eu erat semper rutrum.",59);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("volutpat ornare, facilisis eget,",16);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("eget lacus. Mauris non dui nec",38);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nunc sit amet metus. Aliquam",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("diam. Duis mi enim, condimentum eget,",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("libero. Donec consectetuer mauris id sapien. Cras dolor dolor,",48);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Praesent eu",58);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("mauris id sapien. Cras dolor dolor, tempus non,",51);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dis parturient montes, nascetur ridiculus mus. Donec dignissim magna",6);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("et risus. Quisque libero lacus, varius et, euismod",6);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("urna. Nunc quis arcu",39);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Sed nec metus facilisis lorem tristique aliquet.",1);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("semper egestas, urna justo faucibus lectus, a sollicitudin orci",33);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("at, nisi. Cum",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam",8);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("faucibus ut,",8);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dolor. Fusce",14);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("rutrum.",43);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem",42);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("quam. Curabitur vel lectus. Cum sociis natoque penatibus",48);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("laoreet,",59);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("habitant morbi tristique senectus et netus",52);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nec tellus.",11);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("morbi tristique senectus et netus et malesuada",53);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nec,",12);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("placerat, augue. Sed molestie.",52);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("aliquam iaculis, lacus pede sagittis",18);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("erat. Etiam",17);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ornare tortor at",17);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae",57);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("imperdiet non, vestibulum nec, euismod in, dolor. Fusce",16);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("egestas. Duis ac",16);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dui augue eu tellus. Phasellus elit",46);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt",56);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nonummy ac, feugiat non, lobortis",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("id enim. Curabitur massa. Vestibulum accumsan",39);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede. Suspendisse dui.",38);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("aptent taciti",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Sed",36);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Sed et libero.",1);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non, bibendum sed, est. Nunc laoreet lectus quis",38);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sed",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.",30);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("rutrum magna.",57);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vulputate dui,",14);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vitae erat vel pede blandit",8);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Maecenas iaculis aliquet diam.",61);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Morbi sit amet massa. Quisque porttitor eros",46);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus,",32);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("quam dignissim pharetra.",16);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum.",58);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Etiam bibendum fermentum metus.",32);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sociis natoque penatibus et magnis dis parturient montes, nascetur",37);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla.",29);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sem semper erat, in consectetuer ipsum",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Mauris",52);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vitae nibh. Donec est mauris,",55);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ultrices. Duis volutpat nunc sit amet metus. Aliquam erat",28);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("faucibus orci luctus et ultrices",41);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("et magnis dis parturient",22);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("bibendum",3);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("mauris. Suspendisse aliquet molestie tellus. Aenean egestas",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ac mi eleifend egestas.",49);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vitae sodales nisi magna sed dui. Fusce aliquam, enim nec",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("elementum",27);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("malesuada fringilla est. Mauris eu turpis. Nulla",6);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Duis gravida. Praesent eu",3);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("rhoncus. Proin nisl sem, consequat",34);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("massa lobortis ultrices. Vivamus rhoncus. Donec",48);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("posuere vulputate,",8);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ut odio vel est tempor bibendum. Donec felis",47);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("aliquam arcu. Aliquam ultrices iaculis odio.",61);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Duis ac arcu. Nunc mauris.",38);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("rutrum",40);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("magnis dis parturient montes,",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("diam. Proin dolor.",9);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum",61);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dolor",15);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vel pede blandit congue. In scelerisque scelerisque dui.",25);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Nullam enim. Sed nulla",30);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("feugiat tellus",23);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ut cursus luctus,",23);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("in, dolor.",14);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ut, pellentesque eget, dictum placerat, augue. Sed molestie.",31);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Proin nisl sem, consequat nec, mollis vitae,",28);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("luctus. Curabitur egestas nunc",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dapibus id, blandit at, nisi.",59);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Quisque imperdiet, erat nonummy",14);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pharetra. Quisque ac libero nec",18);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("at, egestas a, scelerisque",25);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("est tempor bibendum. Donec felis",35);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Duis",40);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Quisque porttitor eros nec tellus. Nunc lectus",16);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non, bibendum sed, est.",15);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vulputate eu, odio. Phasellus at augue id",26);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("et tristique pellentesque, tellus sem mollis dui, in",9);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Mauris eu turpis. Nulla aliquet. Proin velit. Sed",29);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("varius. Nam porttitor scelerisque neque. Nullam",55);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("urna suscipit nonummy. Fusce fermentum",54);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("feugiat tellus lorem eu metus. In",37);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tincidunt orci quis lectus.",3);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Fusce mollis. Duis sit amet diam eu",1);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("cursus purus. Nullam scelerisque neque sed sem egestas",52);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("metus sit",18);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("lobortis quis, pede. Suspendisse dui. Fusce diam",18);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nec luctus felis purus ac tellus. Suspendisse sed dolor.",27);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("diam at pretium aliquet, metus urna convallis erat, eget tincidunt",60);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum",45);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("arcu. Vestibulum ante ipsum primis in faucibus orci luctus",22);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Phasellus vitae mauris sit amet lorem",47);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("eu dolor egestas rhoncus. Proin",53);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("ante blandit viverra. Donec tempus, lorem fringilla ornare",15);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("gravida mauris",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("sem ut dolor dapibus gravida.",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("egestas hendrerit neque. In",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("nisi nibh lacinia orci,",13);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("non, bibendum",51);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Nulla interdum.",20);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("congue a, aliquet vel, vulputate eu,",6);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("odio. Etiam ligula",39);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tristique ac, eleifend vitae, erat.",52);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("augue scelerisque mollis. Phasellus",39);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Quisque ac libero nec ligula consectetuer rhoncus. Nullam",55);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant",40);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("elit. Etiam laoreet, libero et",4);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("pede nec ante blandit viverra.",24);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium",10);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("Suspendisse commodo tincidunt nibh. Phasellus nulla.",2);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("tortor, dictum eu, placerat eget, venenatis",50);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("dictum magna.",16);
INSERT INTO `Contributory` (`description`,`nbDays`) VALUES ("montes, nascetur ridiculus mus. Aenean",53);
