INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vehicula","a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam",13,14);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lacus. Etiam","eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut",17,16);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Fusce aliquet","sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et",17,3);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Curabitur egestas","ac nulla. In tincidunt congue turpis. In condimentum. Donec at",36,24);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("dolor vitae dolor.","vitae risus. Duis a",13,20);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("tincidunt pede","et netus et malesuada fames",25,7);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Duis","dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per",39,18);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("eleifend egestas.","arcu. Vestibulum ante ipsum",17,21);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lectus ante dictum","sed tortor. Integer",31,1);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("nec quam.","libero mauris,",35,23);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("pellentesque eget, dictum","pede ac urna. Ut tincidunt vehicula",21,13);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("leo.","aptent taciti sociosqu",48,10);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vitae, erat. Vivamus","libero",46,14);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("dictum mi, ac","Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim,",26,1);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("morbi tristique","mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur",50,8);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("in faucibus orci","Fusce aliquet magna a neque. Nullam",21,23);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vitae","nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet",44,2);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("semper rutrum.","Vestibulum accumsan neque et",28,10);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Suspendisse","ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas",35,19);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("aliquet","eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc",19,24);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Praesent luctus.","sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam",21,18);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Aliquam","lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi",45,6);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("scelerisque dui.","orci. Phasellus dapibus quam quis diam. Pellentesque",22,17);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("condimentum.","dictum mi, ac mattis velit justo",49,11);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("habitant","sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec",17,9);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("ipsum porta elit,","vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem.",32,10);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("mauris, rhoncus","natoque penatibus et magnis dis parturient montes, nascetur ridiculus",16,13);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Nunc ac","dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra.",13,17);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("elit","a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus",36,14);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("velit eu sem.","Fusce aliquet magna a neque. Nullam ut nisi a odio semper",9,18);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("a odio semper","magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed",35,21);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("nascetur","pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis",49,26);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("convallis, ante lectus","eu lacus. Quisque imperdiet,",16,11);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Morbi accumsan","nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi",32,13);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Nunc mauris sapien,","ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet",32,7);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Maecenas iaculis","Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet.",24,5);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("eu, placerat eget,","tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi.",10,18);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Integer vitae","est tempor bibendum. Donec",10,20);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("pede,","Aenean egestas hendrerit neque. In",34,23);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("dui","dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus",30,7);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("magnis","orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In",16,3);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("pellentesque","neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem",37,17);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("diam","malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris",29,16);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("neque venenatis lacus.","ultrices. Duis volutpat nunc sit amet metus.",15,18);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("cursus,","torquent per conubia nostra,",42,20);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("sed, hendrerit","ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis",27,7);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Cras","a mi fringilla mi lacinia mattis. Integer eu lacus.",48,1);
INSERT INTO `project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Duis","fringilla purus mauris a nunc. In at pede.",42,1);
