INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("at, velit.","volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede",42,57);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lectus rutrum urna,","aliquam arcu. Aliquam",32,79);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("leo. Vivamus","laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit",22,44);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("dui. Cras pellentesque.","ac urna. Ut tincidunt vehicula risus.",18,15);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("netus et","justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed",45,28);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vel,","egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis.",19,13);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Cras dictum ultricies","sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam",20,48);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lacinia mattis.","adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim",21,60);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lobortis ultrices.","sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan",9,25);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("mauris sit","lobortis risus. In mi pede, nonummy ut, molestie",31,21);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vestibulum lorem, sit","diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean",28,62);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Nulla tempor augue","egestas lacinia. Sed congue, elit sed",26,24);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("et libero. Proin","eu, euismod ac, fermentum vel, mauris.",44,79);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lorem","odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies",38,97);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("feugiat placerat","elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar",32,79);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("in","egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras",17,100);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("augue.","lorem fringilla ornare placerat,",9,74);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("orci","Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec",12,100);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Phasellus dapibus quam","Morbi metus.",22,72);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("purus","lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non",22,80);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("nec quam.","ridiculus mus. Donec dignissim magna a tortor.",14,32);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lobortis quam a","at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante",33,23);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("risus. Nunc ac","egestas. Duis ac arcu.",14,99);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("diam.","ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas",27,29);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("massa.","dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae",37,23);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("consequat dolor","sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam",16,34);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("consequat nec,","malesuada vel,",45,58);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Phasellus vitae mauris","Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam",20,6);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("enim. Curabitur","in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare",39,18);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("tellus justo sit","nibh.",33,40);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lectus pede,","non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna.",36,43);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("sodales","imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in,",40,70);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("erat volutpat. Nulla","arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a,",28,78);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Donec feugiat","Donec tempus, lorem fringilla ornare placerat, orci lacus",46,76);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("enim. Etiam","parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa",45,65);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("volutpat nunc","suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis",24,6);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("elit,","eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat",26,10);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Curae; Phasellus","porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus",11,20);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lectus pede","ipsum leo",50,56);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("convallis","Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras",41,57);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("malesuada","cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida",39,79);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vitae","orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec,",12,33);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("egestas. Fusce","tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla",47,46);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("iaculis","purus. Maecenas libero est, congue a, aliquet vel,",21,26);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("ornare","tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum",16,27);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("diam dictum","sagittis",19,37);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("arcu. Vestibulum","quam. Pellentesque habitant",11,11);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lacus. Aliquam","vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus,",50,96);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("consectetuer rhoncus.","diam at pretium aliquet, metus urna convallis erat, eget tincidunt",12,6);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("risus.","iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus",39,95);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("dui,","lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel",41,50);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("pellentesque.","at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.",12,24);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("consectetuer ipsum nunc","ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis",31,77);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("habitant morbi","interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est,",35,88);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("at augue","scelerisque sed, sapien. Nunc pulvinar arcu et pede.",19,60);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Integer vitae nibh.","dignissim lacus. Aliquam rutrum lorem",36,66);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("imperdiet ullamcorper.","enim.",43,89);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("pharetra nibh. Aliquam","ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec",38,64);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Duis ac arcu.","iaculis odio. Nam interdum enim non nisi.",28,76);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Morbi sit","felis, adipiscing fringilla,",14,21);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vulputate eu,","orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est",49,64);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("accumsan","scelerisque sed, sapien. Nunc",37,61);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Etiam","ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras",20,50);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Maecenas mi felis,","sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse",36,53);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Cras","euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris",22,38);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("neque","odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada",27,40);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Etiam imperdiet dictum","Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus",45,81);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("mauris","dolor",49,1);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("id,","a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec,",35,88);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("eros turpis non","interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam",22,97);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("hendrerit. Donec","ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac",36,67);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("fames ac","purus,",18,99);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("nec ante. Maecenas","feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut,",46,87);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("augue scelerisque","tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing.",38,51);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("luctus sit amet,","quis accumsan convallis,",9,20);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("nunc sed","Duis",43,38);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Donec","nec",29,41);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("ornare.","tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna",27,4);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Integer sem elit,","diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula.",11,30);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Donec tincidunt. Donec","quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt",11,72);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("auctor non,","non quam. Pellentesque habitant morbi tristique senectus et netus",38,4);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vel,","cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent",33,27);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("est ac mattis","quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc",23,44);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lorem eu","neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum",14,51);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("nunc sit amet","mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat.",8,75);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("lorem","odio sagittis semper. Nam",34,21);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("non,","tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et,",37,76);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("vel","urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien.",46,40);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("elit, pharetra","Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut",21,22);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("et","pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue",46,91);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Proin","sollicitudin a, malesuada",38,16);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("Integer","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in",17,50);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("quam. Pellentesque habitant","dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et",11,16);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("nonummy. Fusce fermentum","metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec",40,91);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("a","purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas",29,86);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("ligula. Nullam enim.","nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus",42,86);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("amet,","sed, facilisis vitae, orci. Phasellus dapibus quam quis",34,75);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("sit","Donec elementum,",24,60);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("egestas. Duis ac","sociosqu ad litora",44,63);
INSERT INTO `Project` (`name`,`description`,`dailyRate`,`idCustomer`) VALUES ("per inceptos hymenaeos.","parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed",37,2);
